compilation_unit: package_decl? import_decl? type_decl*

package_decl: PACKAGE_KW package_name ";"

import_decl: single_type_import_decl | type_import_on_demand_decl
single_type_import_decl: IMPORT_KW type_name ";"
type_import_on_demand_decl: IMPORT_KW IDENTIFIER "." import_rest ";"
import_rest: "*"
			| (IDENTIFIER ".") import_rest

type_decl: class_declaration
		// | interface_declaration
		| SEMICOLON
