SQ_BRACKETS: "[]"

EQ: "=="
NOT_EQ: "!="
LOGICAL_OR: "||"
LOGICAL_AND: "&&"
EAGER_OR: "|"
EAGER_AND: "&"

LT: "<"
GT: ">"
LT_EQ: "<="
GT_EQ: ">="

LINE_TERMINATOR: "\r" | "\n" | "\r\n"
WHITESPACE: " " | "\f" | "\t"

// INPUT_CHAR: /(?!(\r|\n))[\x00-\x7F]/

TRADITIONAL_COMMENT: /\/\*[\x00-\x7F]*?(\*\/)/
END_OF_LINE_COMMENT: /\/\/((?!(\r|\n))[\x00-\x7F])*(\r|\n|\r\n)/

%ignore TRADITIONAL_COMMENT
%ignore END_OF_LINE_COMMENT
%ignore LINE_TERMINATOR
%ignore WHITESPACE
