type: PRIMITIVE_TYPE | reference_type

PRIMITIVE_TYPE: NUMERIC_TYPE | BOOLEAN_KW
NUMERIC_TYPE: BYTE_KW | SHORT_KW | INT_KW | CHAR_KW // no long or floats

?reference_type.1: type_name | ARRAY_TYPE
ARRAY_TYPE: (NAME | BYTE_KW | SHORT_KW | INT_KW | CHAR_KW | BOOLEAN_KW) SQ_BRACKETS

NAME: IDENTIFIER ("." IDENTIFIER)*

?type_name: NAME
class_type: NAME
interface_type: NAME

package_name: NAME
package_or_type_name: NAME
method_name: NAME
expression_name: NAME
