type: primitive_type | reference_type

?primitive_type: numeric_type | BOOLEAN_KW
?numeric_type: BYTE_KW | SHORT_KW | INT_KW | CHAR_KW // no long or floats

reference_type.1: type_name | type SQ_BRACKETS

type_name: IDENTIFIER ("." IDENTIFIER)*

class_type: type_name
interface_type: type_name

package_name: type_name
package_or_type_name: type_name
method_name: type_name
expression_name: type_name
