type: primitive_type | reference_type

?primitive_type: numeric_type | BOOLEAN_KW
?numeric_type: BYTE_KW | SHORT_KW | INT_KW | CHAR_KW // no long or floats

?reference_type.1: type_name | array_type
array_type: type_name SQ_BRACKETS | primitive_type SQ_BRACKETS

name: IDENTIFIER ("." name)*

type_name: name
class_type: name
interface_type: name

package_name: name
method_name: name
expression_name: name
